name: Check links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 0"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
