name: Check links

on:
  push:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "27 0 * * 0"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --insecure --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst'
